server {
    listen 3000;
    server_name localhost;

    resolver 127.0.0.11 valid=5s;
    set $backend_upstream http://backend:8080;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass $backend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
