FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY docs ./docs
COPY BARCAN-*.md ./
COPY src ./src
RUN mvn -q package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
COPY docs ./docs
COPY BARCAN-*.md ./
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
