version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ML_SERVICE_URL=http://ai-service:8000
    depends_on:
      - ai-service

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  ai-service:
    build:
      context: .
      dockerfile: Dockerfile.ai
    ports:
      - "8000:8000"

networks:
  default:
    name: eneik-net
